### ISSUE TITLE
Now i have a problem in install

### ISSUE THREAD

**Issue by Layty** [YYago/summarybuilder#2]
can i speak chinese ...

Now i have a problem in install

$ npm install
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm notice created a lockfile as package-lock.json. You should commit this file.
added 288 packages in 22.135s

Administrator@PC-20171219QREO MINGW32 ~/Desktop/4/Import/thisisatest/node_modules/summarybuilder (master)
$ summary
bash: summary: command not found

**Comment by YYago** [comment]
@Layty 
WARN 信息可以忽略的。

command not found ！ 可能是权限问题，当然，单独的summary 命令（不带参数）是没有响应的。试下 `summary -c` 。

现在才发现连 help 都没有加进去!!!呵呵，算了。大概看下readme吧（大概的意思就是：Google直译，反正也不会翻译正确）。

看你的ID有点印象，看云文档建议用这个：[kc-cli](https://www.npmjs.com/package/kc-cli)  带监视任务，可自动完成一些事情。
